version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "daily"
      timezone: "Asia/Tokyo"
    groups:
      dependencies:
        dependency-type: "production"
        update-types:
          - "patch"
      devDependencies:
        dependency-type: "development"
        update-types:
          - "patch"
    ignore:
      - dependency-name: "vitest"
