version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "saturday"
      time: "15:30"
      timezone: "Asia/Tokyo"
    groups:
      dependencies:
        dependency-type: "production"
        update-types: "patch"
      devDependencies:
        dependency-type: "development"
        pdate-types: "patch"
