version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "saturday"
      time: "15:45"
      timezone: "Asia/Tokyo"
    groups:
      dependencies:
        dependency-type: "production"
        update-types:
          - "patch"
          - "minor"
      devDependencies:
        dependency-type: "development"
        update-types:
          - "patch"
          - "minor"
    ignore:
      - dependency-name: "vitest"
