name = "media-proxy-worker"
main = "src/index.ts"
compatibility_date = "2024-01-17"
workers_dev = false
minify = true
compatibility_flags = [ "nodejs_compat" ]

[vars]
ENV = "production"
AVATAR_REDIRECT_ENABLED = true
AVATAR_REDIRECT_HOST = "example.com"
CLOUD_LOGGING_ENABLED = false
